"""
Django settings for multila project.

**DEVELOPMENT SETTINGS. DO NOT USE IN PRODUCTION!**

This is a settings file for CI runnsers. Production settings are in `settings_prod.py`.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-76tpm66^c=!&)qg5^&%o!9&fo+4wj7ksopfz_@_qty@=1ex$kt"

ALLOWED_HOSTS = []
CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    "api.apps.ApiConfig",
    "django.contrib.admin.apps.SimpleAdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "multila.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "multila.wsgi.application"

CSRF_FAILURE_VIEW = "api.views.csrf_failure"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Berlin"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR.parent / "static_files"
DATA_EXPORT_DIR = BASE_DIR.parent / "data" / "export"
CODEBOOK_PATH = BASE_DIR.parent / "data" / "codebook.pdf"
APPS_DEPLOYMENT = None
CHATBOT_API = {  # set to None to disable chatbot API feature
    "providers": {  # note that the provider name is not allowed to use the string ' | '
        "test": {
            "key": "simulate-only",
            "provider": "openai",
            "available_models": ["gpt-3.5-turbo", "gpt-4o-mini", "gpt-4o"],
        },
    },
    "content_section_identifier_pattern": r"mainContentElem-\d+$",
    "system_role_templates": {  #  per language
        "en": "You are a teacher in data science and statistics. Consider the following learning material enclosed "
        'by "---" marks. Before each content section in the document, there is a unique identifier for that '
        'section denoted as "mainContentElem-#". "#" is a placeholder for a number.'
        "\n\n---\n\n$doc_text\n\n---\n\nNow give a short answer to the following question and, if possible, refer to "
        "the learning material. If you are referring to the learning material, end your answer with a new paragraph "
        'containing only "mainContentElem-#" and replace "#" with the respective section number.',
        "de": "Sie sind Lehrkraft im Bereich Data Science und Statistik. Berücksichtigen Sie das folgende "
        'Lehrmaterial, das durch "---"-Markierungen eingeschlossen ist. Vor jedem Inhaltsabschnitt im Dokument '
        'gibt es eine eindeutige Kennung für diesen Abschnitt, die mit "mainContentElem-#" angegeben ist. "#" '
        "ist ein Platzhalter für eine Zahl.\n\n---\n\n$doc_text\n\n---\n\nGeben Sie nun eine kurze Antwort auf "
        "die folgende Frage und beziehen Sie sich, wenn möglich, auf das Lehrmaterial. Wenn Sie sich auf das "
        'Lehrmaterial beziehen, beenden Sie Ihre Antwort mit einem neuen Absatz, der nur "mainContentElem-#" '
        'enthält und ersetzen Sie "#" durch die entsprechende Abschnittsnummer.',
    },
    "user_role_templates": {  #  per language
        "en": "$question",
        "de": "$question",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
