version: '2'

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080

  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - '../data/db:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=multila'
