version: '2'

services:
  adminer:
    container_name: multila-adminer
    image: adminer
    ports:
      - 8080:8080

  db:
    container_name: multila-db
    image: postgres
#    ports:
#      - '5432:5432'
    volumes:
      - '../data/db:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=multila'
  web:
    container_name: multila-web
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../src:/code
    ports:
      - "8000:8000"
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=multila'
    depends_on:
      - db
