# Generated by Django 4.1.7 on 2023-03-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userapplicationsession',
            constraint=models.UniqueConstraint(fields=('application_session', 'code'), name='unique_appsess_code'),
        ),
    ]
