# Generated by Django 4.1.7 on 2023-03-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_applicationsession_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapplicationsession",
            name="code",
            field=models.CharField(max_length=64, verbose_name="Unique user session code"),
        ),
    ]
