# Generated by Django 4.1.7 on 2023-03-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_trackingsession_device_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackingsession",
            name="start_time",
            field=models.DateTimeField(verbose_name="Session start"),
        ),
    ]
