# Generated by Django 4.1.7 on 2023-03-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_trackingsession_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackingsession",
            name="device_info",
            field=models.JSONField(blank=True, null=True, verbose_name="User device information"),
        ),
    ]
