# Generated by Django 4.1.7 on 2023-03-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_trackingsession_device_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackingevent",
            name="value",
            field=models.JSONField(blank=True, null=True, verbose_name="Event value"),
        ),
    ]
