# Generated by Django 4.2 on 2023-05-02 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_trackingevent_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='default_application_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.applicationsession'),
        ),
    ]
