# Generated by Django 4.2.3 on 2023-08-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_userfeedback_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="text",
            field=models.TextField(blank=True, default=None, null=True, verbose_name="Feedback text"),
        ),
    ]
