# Generated by Django 4.2.8 on 2023-12-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_applicationsessiongate'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsessiongate',
            name='label',
            field=models.CharField(default='', help_text='A unique label to identify this application gate.', max_length=128, verbose_name='Label'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationsessiongate',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2048, verbose_name='Description'),
        ),
    ]
