# Generated by Django 4.2.8 on 2023-12-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_applicationsessiongate_last_forward_index_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='applicationsessiongate',
            constraint=models.UniqueConstraint(fields=('label',), name='unique_label'),
        ),
    ]
