# Generated by Django 4.2.14 on 2024-08-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_applicationsession_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsessiongate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
