# Generated by Django 4.2.16 on 2024-10-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_application_local_appdir'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfig',
            name='app_content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Application content'),
        ),
    ]
