# Generated by Django 4.2.16 on 2024-10-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_applicationconfig_app_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationconfig',
            name='app_content',
            field=models.TextField(blank=True, default=None, help_text='Learning app content as retrieved from the app URL and processed for usage with the chatbot API.', null=True, verbose_name='Application content'),
        ),
    ]
