# Generated by Django 4.2.16 on 2024-10-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_applicationconfig_app_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplicationsession',
            name='chatbot_communication',
            field=models.JSONField(blank=True, null=True, verbose_name='Previous chatbot communication'),
        ),
    ]
